import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'
import { initSentry } from './lib/sentry'
import ErrorBoundary from './components/ui/ErrorBoundary'

initSentry()

// Install the PWA service worker (generated by vite-plugin-pwa → /sw.js) so the
// full app shell is cached and the app loads with zero network — field workers
// underground / on rural rooftops. The SW uses skipWaiting + clientsClaim +
// autoUpdate, so a new deploy is fetched and applied on the next load (no
// stale-bundle lock). Registered directly to avoid pulling workbox-window into
// the client bundle (which rolldown can't resolve from virtual:pwa-register).
if ('serviceWorker' in navigator && import.meta.env.PROD) {
  window.addEventListener('load', () => {
    void navigator.serviceWorker.register('/sw.js', { scope: '/' })
  })
}

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </StrictMode>,
)
