import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.tsx'
import { initSentry } from './lib/sentry'
import ErrorBoundary from './components/ui/ErrorBoundary'
import { initServiceWorkerUpdates } from './lib/swUpdate'

initSentry()

// Install the PWA service worker (generated by vite-plugin-pwa → /sw.js) so the
// full app shell is cached and the app loads with zero network — field workers
// underground / on rural rooftops. Registered directly to avoid pulling
// workbox-window into the client bundle (which rolldown can't resolve from
// virtual:pwa-register).
//
// `skipWaiting` + `clientsClaim` reiškia, kad naujas apvalkalas perima valdymą
// iš karto, BET jau įkeltas puslapis toliau sukasi ant seno kodo. Todėl
// registracija gyvena `swUpdate.ts`, kuris kartu parodo pranešimą apie naują
// versiją — kitaip pirmas apsilankymas po diegimo visada rodo seną.
initServiceWorkerUpdates()

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <ErrorBoundary>
      <App />
    </ErrorBoundary>
  </StrictMode>,
)
