-- ============================================================
-- Migration: fix site_audit_logs SELECT RLS (admin-only)
--
-- ROOT CAUSE of smoke-test failure "[FAIL] 2b installer can read 41
-- audit-log rows": public.site_audit_logs pre-existed in the live DB
-- (created via the dashboard before it was tracked in migrations), so
-- 20260703122000_site_audit_logs.sql's CREATE TABLE IF NOT EXISTS was a
-- no-op AND its DROP POLICY IF EXISTS only removed policies with *our*
-- names. The dashboard-era table carried its own broad SELECT (or FOR ALL)
-- policy with an unknown name — and Postgres permissive policies combine
-- with OR, so that one leftover policy kept granting installers read
-- access despite the new admin-only policy.
--
-- FIX: dynamically drop EVERY existing policy on the table (names are not
-- knowable from the repo), then recreate exactly the intended set:
--   • one SELECT policy  — admin-only;
--   • one INSERT policy  — authenticated, as themselves (audit events are
--     generated by installer actions: checklist updates, status changes);
--   • no UPDATE/DELETE policies (append-only through the API).
-- ============================================================

ALTER TABLE public.site_audit_logs ENABLE ROW LEVEL SECURITY;

-- Drop ALL policies on site_audit_logs, whatever they are named. This is the
-- only reliable way to remove dashboard-created policies whose names the repo
-- never knew. (Known repo names are listed below for documentation; the DO
-- block covers those too, so order does not matter.)
--   Known repo names: "site_audit_logs: matyti tik adminams",
--                     "site_audit_logs: rašyti savo vardu"
--   Suspected dashboard names: e.g. "Enable read access for all users".
DO $drop_all$
DECLARE
  pol RECORD;
BEGIN
  FOR pol IN
    SELECT policyname
    FROM pg_policies
    WHERE schemaname = 'public' AND tablename = 'site_audit_logs'
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON public.site_audit_logs', pol.policyname);
    RAISE NOTICE 'Dropped policy on site_audit_logs: %', pol.policyname;
  END LOOP;
END
$drop_all$;

-- Exactly ONE SELECT policy: admins only.
CREATE POLICY "Admins can read site audit logs" ON public.site_audit_logs
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

-- INSERT stays available to authenticated users acting as themselves, so
-- installer-triggered audit events (checklist_update, status_change, …) keep
-- being recorded. Same definition as 20260703122000.
CREATE POLICY "site_audit_logs: rašyti savo vardu" ON public.site_audit_logs
  FOR INSERT
  TO authenticated
  WITH CHECK (actor_id = auth.uid() OR actor_id IS NULL OR public.is_admin());

-- No UPDATE/DELETE policies are created (deny by default under RLS), and the
-- grants are trimmed to match — the log is append-only via the API.
REVOKE UPDATE, DELETE ON public.site_audit_logs FROM authenticated;
GRANT SELECT, INSERT ON public.site_audit_logs TO authenticated;

SELECT pg_notify('pgrst', 'reload schema');

-- ════════════════════════════════════════════════════════════
-- VERIFICATION (manual, dev/staging)
-- ────────────────────────────────────────────────────────────
-- (a) Policy inventory — expect EXACTLY these two rows:
--   select policyname, cmd from pg_policies
--   where schemaname='public' and tablename='site_audit_logs' order by 1;
--   -- "Admins can read site audit logs"    | SELECT
--   -- "site_audit_logs: rašyti savo vardu" | INSERT
--
-- (b) Re-run supabase/tests/rls_smoke_test.sql — expect:
--   [PASS] 2b installer sees 0 audit-log rows
--   [PASS] 1d admin reads site_audit_logs (...)
-- ════════════════════════════════════════════════════════════
